package estructuraDatos;

public enum TipoMedicamento {
    ANALGESICOS,
    LAXANTES,
    ANTIINFECCIOSOS,
    ANTIDEPRESIVOS,
    ANTITUSIVOS,
    MUCOLITICOS,
    ANTIACIDOS,
    ANTIULCEROSOS,
    ANTIALERGICOS,
    ANTIFIARREICOS
}
